services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_DB: things_review
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

